name: dart_softcorp_blocks
description: gRPC files from softcorp blocks
version: 0.0.1
homepage: https://github.com/softcorp-io

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  protobuf: ^2.0.1
  grpc: ^3.0.2

dev_dependencies:
  lints: ^1.0.0
