name: nuntio_blocks
description: gRPC files for nuntio blocks
version: 0.0.19
homepage: https://github.com/nuntiodev

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  protobuf: ^2.0.1
  grpc: ^3.0.2
  fixnum: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
