name: flutter_hera
description: gRPC files for Hera
version: 0.0.16
homepage: https://github.com/nuntiodev

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.1
  grpc: ^3.0.2
  fixnum: ^1.0.0
  dart_nuntio_cloud: ^0.0.2
  animate_do: ^2.1.0
  sleek_circular_slider: ^2.0.1
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^10.1.0
  dart_jsonwebtoken: ^2.4.1
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.3.0
  uuid: ^3.0.6
  pinput: ^2.2.8
  device_info_plus: ^3.2.3
  shared_preferences: ^2.0.13
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  flutter_svg: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
